### ISSUE TITLE
Implement automatic scaling of canvas rendered UI elements or text labels depending on the grid size and zoom level

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#1104]
Description: Currently large maps (150 + ft.) are abnoxious as if you are zoomed out enough to see the enemy you cannot measure distance as the distance displays as tiny

**Comment by guldelox** [comment]
Is this still being considered? There is at least one module that handles this, but this seems like something that ought to be core functionality.

**Comment by aaclayton** [comment]
It is not currently being worked on, but it remains an open issue for future consideration.

**Comment by guldelox** [comment]
Sounds good! I'm running Storm King's Thunder in DnD5e, and the giant-sized dungeons make it almost impossible to read the measurement or template tools when zoomed out!

**Comment by dev7355608** [comment]
Originally in GitLab by @ imposeren

### Feature Summary

When zoomed out, labels for distance ruler or for measurement templates can be hard to see, so font-size for these label should depend on current zoom level.

### Example implementation

```diff
--- foundry.js.bak      2020-04-20 06:31:42.586803083 +0200
+++ foundry.js  2020-04-21 21:01:40.904883984 +0200
@@ Just add this new function somewhere in foundry.js @@
+function scaledTextStyle() {
+  const style = CONFIG.canvasTextStyle.clone();
+  if (canvas.stage.scale._x < 1) {
+    style.fontSize = Math.round(style.fontSize/canvas.stage.scale._x);
+  }
+  return style
+}
@@ change `MeasuredTemplate.draw` @@
     this.controlIcon = this.addChild(this._drawControlIcon());

     // Draw the ruler measurement
-    this.ruler = this.addChild(new PIXI.Text(null, CONFIG.canvasTextStyle.clone()));
+    this.ruler = this.addChild(new PIXI.Text(null, scaledTextStyle()));

     // Update the shape and highlight grid squares
     this.refresh();
@@ change `Ruler._onAddWaypoint` @@
     let cursor = event.data.getLocalPosition(canvas.grid),
         waypoint = new PIXI.Point(...canvas.grid.getCenter(cursor.x, cursor.y));
     this.waypoints.push(waypoint);
-    this.labels.addChild(new PIXI.Text("", CONFIG.canvasTextStyle));
+    this.labels.addChild(new PIXI.Text("", scaledTextStyle()));
   }

   /* -------------------------------------------- */
@@ change `Ruler.update` @@

     // Ensure labels are created
     for ( let i=0; i<this.waypoints.length - this.labels.children.length; i++) {
-      this.labels.addChild(new PIXI.Text("", CONFIG.canvasTextStyle));
+      this.labels.addChild(new PIXI.Text("", scaledTextStyle()));
     }

     // Measure current distance
```

Tested this in Google chrome: works as expected. 

Potential issues: if you zoom in/out when labels are already drawn, then their style will not be updated. This can be fixed by adding `Hooks.on("canvasPan", (canvas, options) => {...})` But I don't think that it's good idea


### Extra

Similar thing can be done with token nameplates, but I think it should only affect "on hover" nameplates, because otherwise there is a high risk that nameplates will overlap one another


### Priority/Importance

Low impact because it's not often that you need to measure large distances.

**Comment by dev7355608** [comment]
Related issue: #4920.

**Comment by aaclayton** [comment]
Our new V13 approach to ruler measurement and labels have improved legibility across the board. They do not remain fixed size regardless of zoom level, but this is (arguably, according to our team's opinion) no longer necessary with the other changes.

**Comment by aaclayton** [comment]
@Pfodge I think you misunderstood my comment. We implemented dynamic text sizing relative to grid size, *not* zoom level.

**Comment by aaclayton** [comment]
The size of labels in a 50px grid in V13 should be double what it was in V12 because text sizes are normalized relative to a 100px grid. If you are not observing labels that are twice as large in V13 as in V12 (for a scene with a 50px grid) it is possible that:

1. We missed applying this scaling to certain elements.
2. Your game system is responsible for rendering these labels, rather than the core software, and is not applying this scaling
3. Some other module is interfering

**Comment by Pfodge** [comment]
I see, the grid size being bigger is a reversal of prior knowledge that lower grid sizes increased the relative size of these elements. I messed around on a 200px grid scene in a blank world with no modules installed. Its slightly better but I have to say still not to my preference by default (see how the token HUD buttons are smaller than control buttons). 

![Image](https://github.com/user-attachments/assets/b3cd055d-64ab-47d8-af30-5f8f2b9b0f4a)

Neither UI Scale settings (Interface Scale, Font Size) seem to affect nameplates. Interface Scale doesn't affect the token HUD but it gets messed up (see picture) when Font Size is increased. Font Size affects the ruler but should there not be a core way to alter the scale of these things (nameplates, ruler, token HUD) independently? My preference would be the max Font Size as what the drag ruler should be by default. Is there an internal reason for the pushback against these elements zoom scaling? Is it really hard to implement? 

(P.S. Hope I'm not coming across as a pest, sorry if I am. Just tryng to get what I see as a serious issue sorted)

![Image](https://github.com/user-attachments/assets/78f4b17b-4e5b-4e3c-906b-b3b8d368b854)
