### ISSUE TITLE
The choice between default and shuffled display mode in the Cards sheet is no longer persisted (affects v10.272)

### ISSUE THREAD

**Issue by admiralnlson** [foundryvtt/foundryvtt#7465]
### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: 10.272
* Operating System: Windows w/ Node.js
* How Are You Using Foundry: Chrome
* Which Game System: N/A
* Modules Enabled?: no

#### Original understanding, debunked by @aaclayton :
~~Shuffling a deck with the default Cards sheet only temporarily reorders cards in the display.~~
~~Re-rendering the sheet (e.g. via F5) loses the shuffle and reverts to a sort based on 'suit' (first) and 'value' (second).~~

#### New understanding:
The user's selection between default and shuffled display mode in the Cards sheet is no longer persisted like it was in v9.

The new behaviour of defaulting back to 'default mode' on each re-render or close/reopen of the sheet could be intentional or a regression. But, if intentional, I would argue it is inferior UX-wise.

**Comment by aaclayton** [comment]
Is this possibly just a misunderstanding that you have the sheet view mode in "default sort" order rather than "shuffled sort" order?

**Comment by admiralnlson** [comment]
@aaclayton I was not aware this button to swap between default and shuffled sorts existed. So thanks for that tip.

However, there is a still a difference between v9 and v10 behaviors, which I think may be a regression:

The choice of default vs shuffled used to be persisted in v9. But in v10, it always defaults back to default mode upon re-render of or closing/reopening the sheet.

I'll rework this issue to be about this.

**Comment by Fyorl** [comment]
I'm not able to reproduce this on the latest dev branch. I've attached a small video that demonstrates shuffling a deck a few times then closing and opening the sheet and re-rendering it. In all cases the choice of shuffled vs. ordered view is retained.

https://user-images.githubusercontent.com/207433/178294135-e42c88ed-41ec-40c3-b8a1-6ad9523198ce.mp4

**Comment by admiralnlson** [comment]
@Fyorl I'm not able to tell with the video if you also tried an F5 also.
But the fact it keeps the display mode after a close/reopen of the sheet seems convincing enough.

Maybe it was another fix merged to develop since 10.272 that fixed it?

I let you decide if you'd rather close this bug as nonrepro or wait until the next official patch when I would test again to confirm/infirm the issue persists on my side.

**Comment by Fyorl** [comment]
I didn't try F5, but that will always reset the sort mode since choice of sort mode is a transient setting that is not persisted, and has never been persisted, even in v9.

**Comment by admiralnlson** [comment]
@Fyorl ah!

Well then it seems the only difference between v9 and v10/develop is that the mode now defaults to 'unshuffled' while it used to default to 'shuffled' in v9.

Hopefully, my understanding is correct this time.

And, if yes, then I would argue that 'shuffled' as the default view mode from v9 was best. Because one used to be able to witness the impact of pushing the "shuffle" button immediately with the default view, whereas now, one may not realize the shuffle worked until they click on the <> butto above the card images.

Anyway, I let you guys figure out the rest. I think you have all elements now to take whatever decision (or lackthereof) is needed here. :)

**Comment by Fyorl** [comment]
I will leave the issue open so we can take a look at whether this default has been changed, and whether it was intentional or not.

**Comment by Fyorl** [comment]
I was able to confirm that the default starting sort mode inadvertently changed between v9 and v10, and has now been reverted.

I wanted to note that this:
> Because one used to be able to witness the impact of pushing the "shuffle" button immediately with the default view, whereas now, one may not realize the shuffle worked until they click on the <> butto above the card images.

Was still not the case. Clicking the shuffle button will always set the sort mode to SHUFFLED and that behaviour was unchanged in v10.
